- name: 鲫鱼
  minLen: 10
  maxLen: 30
  minW: 0.2
  maxW: 1
  weight: 30
  priceRate: 1.0
  normal: true
- name: 鲤鱼
  minLen: 20
  maxLen: 60
  minW: 0.5
  maxW: 3
  weight: 20
  priceRate: 1.2
  normal: true
- name: 草鱼
  minLen: 30
  maxLen: 80
  minW: 1
  maxW: 6
  weight: 15
  priceRate: 1.1
  normal: true
- name: 锦鲤
  minLen: 15
  maxLen: 50
  minW: 0.3
  maxW: 2
  weight: 8
  priceRate: 2.0
  normal: false
- name: 胖头鱼
  minLen: 25
  maxLen: 70
  minW: 1
  maxW: 5
  weight: 10
  priceRate: 1.3
  normal: true
- name: 鲈鱼
  minLen: 15
  maxLen: 40
  minW: 0.3
  maxW: 1.5
  weight: 8
  priceRate: 1.5
  normal: true
- name: 猫猫鱼
  minLen: 10
  maxLen: 25
  minW: 0.2
  maxW: 0.8
  weight: 5
  priceRate: 2.5
  normal: false
- name: 金龙鱼
  minLen: 40
  maxLen: 100
  minW: 2
  maxW: 10
  weight: 3
  priceRate: 5.0
  normal: false
- name: 神秘鱼
  minLen: 50
  maxLen: 120
  minW: 5
  maxW: 20
  weight: 1
  priceRate: 10.0
  normal: false
- name: 几把鱼
  minLen: 5
  maxLen: 15
  minW: 0.1
  maxW: 0.5
  weight: 1
  priceRate: 0.1
  normal: false
- name: 黑鱼
  minLen: 30
  maxLen: 70
  minW: 1
  maxW: 5
  weight: 10
  priceRate: 1.3
  normal: true
- name: 鳗鱼
  minLen: 40
  maxLen: 100
  minW: 1.5
  maxW: 6
  weight: 6
  priceRate: 2.0
  normal: true
- name: 河豚
  minLen: 10
  maxLen: 25
  minW: 0.3
  maxW: 1
  weight: 4
  priceRate: 3.0
  normal: false
- name: 皮卡鱼
  minLen: 8
  maxLen: 20
  minW: 0.2
  maxW: 0.6
  weight: 3
  priceRate: 4.0
  normal: false
- name: 鲨鱼
  minLen: 50
  maxLen: 120
  minW: 5
  maxW: 12
  weight: 2
  priceRate: 5.0
  normal: false
- name: 斑点狗鱼
  minLen: 25
  maxLen: 60
  minW: 1
  maxW: 4
  weight: 9
  priceRate: 1.8
  normal: true
- name: 魔鬼鱼
  minLen: 80
  maxLen: 150
  minW: 8
  maxW: 20
  weight: 1
  priceRate: 10.0
  normal: false
- name: 泥鳅
  minLen: 10
  maxLen: 20
  minW: 0.1
  maxW: 0.3
  weight: 20
  priceRate: 0.8
  normal: true
- name: 拉普拉斯鱼
  minLen: 30
  maxLen: 70
  minW: 2
  maxW: 6
  weight: 2
  priceRate: 6.0
  normal: false
- name: 克苏鲁鱼
  minLen: 60
  maxLen: 130
  minW: 5
  maxW: 15
  weight: 1
  priceRate: 9.9
  normal: false
- name: 银鳞鱼
  minLen: 12
  maxLen: 28
  minW: 0.2
  maxW: 0.9
  weight: 25
  priceRate: 1.1
  normal: true
- name: 黑鲷
  minLen: 20
  maxLen: 50
  minW: 0.8
  maxW: 2.5
  weight: 12
  priceRate: 1.6
  normal: true
- name: 红魔鱼
  minLen: 35
  maxLen: 75
  minW: 1.5
  maxW: 4.5
  weight: 6
  priceRate: 2.2
  normal: false
- name: 冰晶鱼
  minLen: 25
  maxLen: 60
  minW: 0.7
  maxW: 3.5
  weight: 7
  priceRate: 2.8
  normal: false
- name: 火羽鱼
  minLen: 10
  maxLen: 22
  minW: 0.2
  maxW: 0.6
  weight: 5
  priceRate: 3.0
  normal: false
- name: 青铜鱼
  minLen: 18
  maxLen: 38
  minW: 0.4
  maxW: 1.2
  weight: 14
  priceRate: 1.4
  normal: true
- name: 泥塘鲶
  minLen: 20
  maxLen: 55
  minW: 1
  maxW: 3.8
  weight: 9
  priceRate: 1.7
  normal: true
- name: 幽影鱼
  minLen: 30
  maxLen: 70
  minW: 2
  maxW: 5
  weight: 2
  priceRate: 4.5
  normal: false
- name: 风铃鱼
  minLen: 12
  maxLen: 30
  minW: 0.3
  maxW: 0.8
  weight: 6
  priceRate: 2.0
  normal: false
- name: 琉璃鱼
  minLen: 45
  maxLen: 95
  minW: 2.5
  maxW: 8
  weight: 2
  priceRate: 6.5
  normal: false
- name: 冰雪鲤
  minLen: 20
  maxLen: 50
  minW: 0.6
  maxW: 2.2
  weight: 7
  priceRate: 2.4
  normal: false
- name: 黄金旗鱼
  minLen: 70
  maxLen: 150
  minW: 5
  maxW: 12
  weight: 1
  priceRate: 7.5
  normal: false
- name: 喷火鲈鱼
  minLen: 30
  maxLen: 65
  minW: 1.5
  maxW: 4
  weight: 3
  priceRate: 3.8
  normal: false
- name: 星辉鱼
  minLen: 40
  maxLen: 90
  minW: 2
  maxW: 6
  weight: 3
  priceRate: 5.5
  normal: false
- name: 咕噜鱼
  minLen: 15
  maxLen: 35
  minW: 0.4
  maxW: 1
  weight: 10
  priceRate: 1.2
  normal: true
- name: 闪电鲨
  minLen: 60
  maxLen: 130
  minW: 6
  maxW: 14
  weight: 1
  priceRate: 9.5
  normal: false
- name: 泡泡鱼
  minLen: 10
  maxLen: 20
  minW: 0.2
  maxW: 0.6
  weight: 8
  priceRate: 2.1
  normal: false
- name: 月影鳗
  minLen: 40
  maxLen: 80
  minW: 2
  maxW: 5
  weight: 4
  priceRate: 4.0
  normal: false
- name: 铁甲鱼
  minLen: 25
  maxLen: 60
  minW: 1
  maxW: 3.5
  weight: 5
  priceRate: 3.3
  normal: false
- name: 灵魂鲤
  minLen: 35
  maxLen: 70
  minW: 1
  maxW: 4.2
  weight: 2
  priceRate: 6.2
  normal: false
- name: 巨骨舌鱼
  minLen: 80
  maxLen: 180
  minW: 10
  maxW: 30
  weight: 1
  priceRate: 11.0
  normal: false
- name: 钢鳍鱼
  minLen: 28
  maxLen: 65
  minW: 1.2
  maxW: 4
  weight: 6
  priceRate: 3.0
  normal: false
- name: 暗影魟
  minLen: 60
  maxLen: 140
  minW: 6
  maxW: 18
  weight: 1
  priceRate: 9.0
  normal: false
- name: 光辉灯鱼
  minLen: 15
  maxLen: 35
  minW: 0.3
  maxW: 1
  weight: 7
  priceRate: 2.6
  normal: false
- name: 空洞鱼
  minLen: 50
  maxLen: 110
  minW: 4
  maxW: 10
  weight: 2
  priceRate: 6.8
  normal: false
- name: 翡翠海鲂
  minLen: 40
  maxLen: 85
  minW: 2
  maxW: 5
  weight: 3
  priceRate: 4.5
  normal: false