- name: 鲫鱼
  minLen: 10
  maxLen: 30
  minW: 0.2
  maxW: 1
  weight: 30
  priceRate: 1.0
  normal: true
- name: 鲤鱼
  minLen: 20
  maxLen: 60
  minW: 0.5
  maxW: 3
  weight: 20
  priceRate: 1.2
  normal: true
- name: 草鱼
  minLen: 30
  maxLen: 80
  minW: 1
  maxW: 6
  weight: 15
  priceRate: 1.1
  normal: true
- name: 锦鲤
  minLen: 15
  maxLen: 50
  minW: 0.3
  maxW: 2
  weight: 8
  priceRate: 2.0
  normal: false
- name: 胖头鱼
  minLen: 25
  maxLen: 70
  minW: 1
  maxW: 5
  weight: 10
  priceRate: 1.3
  normal: true
- name: 鲈鱼
  minLen: 15
  maxLen: 40
  minW: 0.3
  maxW: 1.5
  weight: 8
  priceRate: 1.5
  normal: true
- name: 猫猫鱼
  minLen: 10
  maxLen: 25
  minW: 0.2
  maxW: 0.8
  weight: 5
  priceRate: 2.5
  normal: false
- name: 金龙鱼
  minLen: 40
  maxLen: 100
  minW: 2
  maxW: 10
  weight: 3
  priceRate: 5.0
  normal: false
- name: 神秘鱼
  minLen: 50
  maxLen: 120
  minW: 5
  maxW: 20
  weight: 1
  priceRate: 10.0
  normal: false
- name: 几把鱼
  minLen: 5
  maxLen: 15
  minW: 0.1
  maxW: 0.5
  weight: 1
  priceRate: 0.1
  normal: false