- id: fish_small_dry
  name: 小鱼干
  price: 20
  desc: 喵最爱的零食，回复10体力
  category: stamina
  use:
    type: stamina
    value: 10
  max_per_day: -1
  max_per_user_per_day: 100
- id: fish_big_dry
  name: 大包小鱼干
  price: 50
  desc: 喵最爱的零食，回复30体力
  category: stamina
  use:
    type: stamina
    value: 30
  max_per_day: -1
  max_per_user_per_day: 50
- id: glove_moyu
  name: 摸鱼手套
  price: 200
  desc: 装备后摸鱼概率提升20%
  category: glove
  only_once: true
  use:
    type: moyu_glove
    value: 1
  max_per_day: -1
  probability_bonus: 0.2
- id: rod_basic
  name: 初级鱼竿
  price: 500
  desc: 一把普通的鱼竿，钓鱼概率50%
  category: rod
  only_once: true
  use:
    type: diaoyu_rod
    value: 1
  max_per_day: -1
  probability: 0.5
- id: bait_basic
  name: 初级鱼饵
  price: 5
  desc: 初级鱼饵，似乎只能钓到普通鱼
  category: bait
  use:
    type: diaoyu_bait
    value: 1
  max_per_day: -1
- id: bait_mid
  name: 中级鱼饵
  price: 20
  desc: 中级鱼饵，钓到稀有鱼概率提升
  category: bait
  use:
    type: diaoyu_bait_mid
    value: 1
  max_per_day: -1
- id: bait_high
  name: 高级鱼饵
  price: 50
  desc: 高级鱼饵，钓到稀有和传说鱼概率大幅提升
  category: bait
  use:
    type: diaoyu_bait_high
    value: 1
  max_per_day: -1
- id: bait_top
  name: 特级鱼饵
  price: 200
  desc: 特级鱼饵，只能钓到稀有、传说和隐藏鱼
  category: bait
  use:
    type: diaoyu_bait_top
    value: 1
  max_per_day: -1
- id: rod_mid
  name: 中级鱼竿
  price: 1000
  desc: 一把中级鱼竿，钓鱼概率70%
  category: rod
  only_once: true
  use:
    type: diaoyu_rod_mid
    value: 1
  max_per_day: -1
  probability: 0.7
- id: rod_high
  name: 高级鱼竿
  price: 2000
  desc: 一把高级鱼竿，钓鱼概率90%
  category: rod
  only_once: true
  use:
    type: diaoyu_rod_high
    value: 1
  max_per_day: -1
  probability: 0.9
- id: rod_top
  name: 特级鱼竿
  price: 5000
  desc: 一把特级鱼竿，钓鱼概率100%
  category: rod
  only_once: true
  use:
    type: diaoyu_rod_top
    value: 1
  max_per_day: -1
  probability: 1.0