- id: 1
  name: 小鱼干
  price: 20
  desc: 喵最爱的零食，回复10体力
  use:
    type: stamina
    value: 10
  max_per_day: 50
- id: 2
  name: 大包小鱼干
  price: 50
  desc: 喵最爱的零食，回复25体力
  use:
    type: stamina
    value: 25
  max_per_day: 20