- id: 1
  name: 小鱼干
  price: 20
  desc: 喵最爱的零食，回复10体力
  use:
    type: stamina
    value: 10
  max_per_day: 500
- id: 2
  name: 大包小鱼干
  price: 50
  desc: 喵最爱的零食，回复30体力
  use:
    type: stamina
    value: 30
  max_per_day: 200